# INITIAL SETTINGS
data_directory: ./data/
base_url: https://www.cbioportal.org/api/
clinical_data: metabric_clinical.csv
mutation_data: METABRIC_RNA_Mutation.csv
test_size: 0.25
model_directory: ./models/