# INITIAL SETTINGS
data_directory: ./data/
base_url: https://www.cbioportal.org/api/
clinical_data: metabric_clinical.csv
mutation_data: METABRIC_RNA_Mutation.csv
model_directory: ./models/
models:
    model_1:
        name: Decision Tree Classifier
        filename: decision_tree.joblib
        param_grid:
            ccp_alpha: [0.1, 0.01]
            max_depth: [5, 7]
    model_2:
        name: Support Vector Classifier
        filename: support_vector_machine.joblib
        param_grid:
            C: [0.1, 10]
            gamma: [0.1, 0.01]
    model_3:
        name: Random Forest Classifier
        filename: random_forest.joblib
        param_grid:
            max_depth: [8,10]
            n_estimators: [50, 100]
test_split: 0.25